apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-{{ include "homa.prefix" . }}
  labels:
    app.kubernetes.io/name: {{ include "homa.name" . }}
    helm.sh/chart: {{ include "homa.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  strategy:
    type:  {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "homa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "homa.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostNetwork: true
      containers:
      - image: influxdb:latest
        name: influx-db-container
        env:
        - name: TZ
          value: {{ .Values.timezone }}
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: homa-pvc
          subPath: influxdb
      - image: chronograf:latest
        name: chronograf-container
        command: ["chronograf", "--influxdb-url=http://127.0.0.1:8086"]
        env:
        - name: TZ
          value: {{ .Values.timezone }}
        - name: BOLT_PATH
          value: "/var/lib/chronograf/chronograf-v1.db"
        volumeMounts:
        - mountPath: /var/lib/chronograf
          name: homa-pvc
          subPath: chronograf
      volumes:
      - name: homa-pvc
        persistentVolumeClaim:
          claimName: {{ .Values.pvcClaim }}
